master:
  heroku_remote: "git@heroku.com:ruvetia-master.git"
  heroku_app: "ruvetia-master"
  app_url: "http://ruvetia.org"
  heroku_config:
    # Future Heroku configuration is done in here using ENV variables.

staging:
  heroku_remote: "git@heroku.com:ruvetia-staging.git"
  heroku_app: "ruvetia-staging"
  app_url: "http://ruvetia-staging.herokuapp.com"
  heroku_config:
    # Future Heroku configuration is done in here using ENV variables.
